name: 'Notify (IFTTT Integration)'
description: 'Send notification to IFTTT'
author: 'FragnaroK'
branding:
  icon: 'message-circle'
  color: 'red'
inputs:
  type:
    description: 'Notification type (Success, Error, Pending)'
    required: true
    default: 'error'
  repoName:
    description: 'Repository name'
    required: true
    default: ''
  branch:
    description: 'Branch name'
    required: false
    default: ''
  details:
    description: 'Notification message'
    required: false
    default: ''
  repoLink:
    description: 'Repository link'
    required: false
    default: ''
  IFTTT_EVENT: 
    description: 'IFTTT event name'
    required: false
    default: 'ga_notify'
  IFTTT_KEY: 
    description: 'IFTTT key'
    required: true
    default: ''
  HEADER: 
    description: 'IFTTT header'
    required: false
    default: '{"Content-Type": "application/json"}'


runs:
  using: "composite"
  steps:
    - name: Announce execution
      run: echo "Sending notification to IFTTT - ${{ inputs.repoName }} - ${{ inputs.branch}}"
      shell: bash
    - name: Notify execution
      uses: fjogeleit/http-request-action@v1
      with:
        url: "https://maker.ifttt.com/trigger/${{ inputs.IFTTT_EVENT }}/json/with/key/${{ inputs.IFTTT_KEY }}"
        method: 'POST'
        customHeaders: "${{ inputs.HEADER }}"
        data: '{"repoName": "${{ inputs.repoName }} - ${{ inputs.branch }}","status": "${{ inputs.type }}","details": "${{ inputs.details }}","repoLink": "${{ inputs.repoLink }}"}'

