name: 'Notify (IFTTT Integration)'
description: 'Send notification to IFTTT'
inputs:
  type:
    description: 'Notification type (Success, Error, Pending)'
    required: true
    default: 'error'
    type: string
  repoName:
    description: 'Repository name'
    required: true
    default: ''
    type: string
  branch:
    description: 'Branch name'
    required: false
    default: ''
    type: string
  details:
    description: 'Notification message'
    required: false
    default: ''
    type: string
  repoLink:
    description: 'Repository link'
    required: false
    default: ''
    type: string

env: 
  IFTTT_EVENT: 'ga_notify'
  IFTTT_API: 'https://maker.ifttt.com/trigger/$IFTTT_EVENT/json/with/key/ifttt_key'
  HEADER: '{"Content-Type": "application/json"}'

runs:
  using: "composite"
  steps:
    - name: Print params
      run: |
        echo "type: ${{ inputs.type }}"
        echo "repoName: ${{ inputs.repoName }}"
        echo "branch: ${{ inputs.branch }}"
        echo "details: ${{ inputs.details }}"
        echo "repoLink: ${{ inputs.repoLink }}"
        echo "IFTTT_API: $IFTTT_API"
        echo "HEADER: $HEADER"
      shell: bash
